[application]
name = "crystal-forge-ui"
default_platform = "web"

[web.app]
title = "Crystal Forge"

[web.watcher]
reload_html = true
watch_path = ["src"]

[web.resource]
script = ["https://cdn.tailwindcss.com"]

[web.resource.dev]
style = []
