//! Deterministic exported-artifact fixtures.
//!
//! These build real Crystal Forge export documents — with real
//! `cf-model-json-1` semantic digests — so tests and Nix checks exercise the
//! same parsing, digest-verification, and generation path a user's export takes.
//!
//! Following the existing `xccdf-export-fixture` precedent, fixtures are
//! generated by code rather than checked in as opaque files, so they cannot
//! drift away from the interchange contract.

use cf_compliance::canonical::{ImplementationState, PublicationState};
use cf_compliance::digest::{
    BundleMembershipEntry, BundleVersionCanonical, PolicyVersionCanonical,
};
use cf_compliance::xccdf::export_models::{XccdfBundleExport, XccdfPolicyExport};
use cf_compliance::xccdf::xml_writer::write_bundle_xccdf_export;
use serde_json::json;
use uuid::Uuid;

/// Stable identity used by the fixtures.
fn uuid(value: &str) -> Uuid {
    Uuid::parse_str(value).expect("fixture UUID is valid")
}

fn policy_digest(
    name: &str,
    description: Option<&str>,
    policy_type: &str,
    implementation_state: &str,
    execution_phase: &str,
    config: &serde_json::Value,
    compliance_metadata: &serde_json::Value,
    dependencies: &serde_json::Value,
    enabled_by_default: Option<bool>,
) -> String {
    PolicyVersionCanonical {
        name: name.to_string(),
        description: description.map(str::to_string),
        policy_type: policy_type.to_string(),
        implementation_state: implementation_state.to_string(),
        execution_phase: execution_phase.to_string(),
        config: config.clone(),
        compliance_metadata: compliance_metadata.clone(),
        dependencies: dependencies.clone(),
        opaque_xml_digest: None,
        enabled_by_default,
    }
    .compute_digest()
}

/// A policy-set export exercising every generator outcome.
///
/// Contains two convertible policies, one manual policy, one operational
/// policy type, and one policy whose expression is arbitrary Nix. Every policy
/// carries a correct `semantic_digest`, so parsing also verifies digests.
pub fn policy_set_json() -> String {
    let entries: Vec<(&str, &str, &str, &str, &str, serde_json::Value)> = vec![
        (
            "11111111-0000-0000-0000-000000000001",
            "22222222-0000-0000-0000-000000000001",
            "disable-root-ssh-login",
            "custom_check",
            "native",
            json!({
                "mode": "all",
                "rules": [
                    {
                        "field_name": "permitRootLogin",
                        "description": "Root login over SSH must be disabled.",
                        "expression": "config.services.openssh.settings.PermitRootLogin == \"no\"",
                        "strict": true
                    },
                    {
                        "field_name": "passwordAuth",
                        "description": "Password authentication must be disabled.",
                        "expression": "config.services.openssh.settings.PasswordAuthentication == false",
                        "strict": true
                    }
                ]
            }),
        ),
        (
            "11111111-0000-0000-0000-000000000002",
            "22222222-0000-0000-0000-000000000002",
            "require-firewall",
            "custom_check",
            "native",
            json!({
                "expression": "config.networking.firewall.enable == true",
                "strict": true
            }),
        ),
        (
            "11111111-0000-0000-0000-000000000003",
            "22222222-0000-0000-0000-000000000003",
            "require-physical-console-control",
            "custom_check",
            "manual",
            json!({}),
        ),
        (
            "11111111-0000-0000-0000-000000000004",
            "22222222-0000-0000-0000-000000000004",
            "block-critical-cves",
            "require_cve_check",
            "native",
            json!({"config": {"max_critical": 0, "strict": true}}),
        ),
        (
            "11111111-0000-0000-0000-000000000005",
            "22222222-0000-0000-0000-000000000005",
            "audit-rules-present",
            "custom_check",
            "native",
            json!({
                "expression": "builtins.length config.security.audit.rules > 0",
                "strict": true
            }),
        ),
    ];

    let policies: Vec<serde_json::Value> = entries
        .into_iter()
        .map(
            |(lineage_id, version_id, name, policy_type, implementation_state, config)| {
                let compliance_metadata = json!({});
                let dependencies = json!([]);
                let digest = policy_digest(
                    name,
                    None,
                    policy_type,
                    implementation_state,
                    "nix-evaluation",
                    &config,
                    &compliance_metadata,
                    &dependencies,
                    None,
                );
                json!({
                    "lineage_id": lineage_id,
                    "version_id": version_id,
                    "version": "1.0.0",
                    "publication_state": "accepted",
                    "name": name,
                    "policy_type": policy_type,
                    "implementation_state": implementation_state,
                    "execution_phase": "nix-evaluation",
                    "config": config,
                    "compliance_metadata": compliance_metadata,
                    "dependencies": dependencies,
                    "semantic_digest": digest,
                    "canonicalization_version": "cf-model-json-1",
                })
            },
        )
        .collect();

    let mut text = serde_json::to_string_pretty(&json!({
        "schema": "urn:crystal-forge:policy-set:1",
        "version": "1",
        "policies": policies,
    }))
    .expect("fixture serializes");
    text.push('\n');
    text
}

/// A CF-native XCCDF bundle export with correct bundle and per-rule digests.
///
/// The bundle selects two policy versions and deliberately leaves a third
/// unselected, so generation can be shown to honour the exact frozen membership.
pub fn bundle_xccdf_xml() -> String {
    let bundle_id = uuid("aaaaaaaa-0000-0000-0000-00000000000a");
    let bundle_version_id = uuid("bbbbbbbb-0000-0000-0000-00000000000b");

    struct Entry {
        policy_id: Uuid,
        policy_version_id: Uuid,
        name: &'static str,
        description: &'static str,
        policy_type: &'static str,
        implementation_state: ImplementationState,
        config: serde_json::Value,
        compliance_metadata: serde_json::Value,
        selected: bool,
        order: i32,
    }

    let entries = vec![
        Entry {
            policy_id: uuid("11111111-0000-0000-0000-0000000000a1"),
            policy_version_id: uuid("22222222-0000-0000-0000-0000000000a1"),
            name: "require-time-sync",
            description: "The system clock must be synchronised.",
            policy_type: "custom_check",
            implementation_state: ImplementationState::Native,
            config: json!({
                "mode": "all",
                "context": "nixos-configuration",
                "binding": "toplevel",
                "rules": [{
                    "field_name": "timesyncdEnabled",
                    "description": "The time synchronisation service must be enabled.",
                    "expression": "config.services.timesyncd.enable == true",
                    "strict": true
                }]
            }),
            compliance_metadata: json!({
                "identifiers": [{"system": "http://cyber.mil/cci", "value": "CCI-001891"}]
            }),
            selected: true,
            order: 1,
        },
        Entry {
            policy_id: uuid("11111111-0000-0000-0000-0000000000a2"),
            policy_version_id: uuid("22222222-0000-0000-0000-0000000000a2"),
            name: "disable-empty-passwords",
            description: "Empty passwords must not be permitted.",
            policy_type: "custom_check",
            implementation_state: ImplementationState::Native,
            config: json!({
                "mode": "all",
                "context": "nixos-configuration",
                "binding": "toplevel",
                "rules": [{
                    "field_name": "noEmptyPasswords",
                    "description": "Empty passwords must not be accepted by sshd PAM.",
                    "expression": "config.security.pam.services.sshd.allowNullPassword == false",
                    "strict": true
                }]
            }),
            compliance_metadata: json!({
                "identifiers": [{"system": "NIST 800-53 Rev 5", "value": "IA-5"}]
            }),
            selected: true,
            order: 2,
        },
        Entry {
            policy_id: uuid("11111111-0000-0000-0000-0000000000a3"),
            policy_version_id: uuid("22222222-0000-0000-0000-0000000000a3"),
            name: "unselected-baseline-policy",
            description: "This policy is deselected in this bundle version.",
            policy_type: "custom_check",
            implementation_state: ImplementationState::Native,
            config: json!({
                "mode": "all",
                "context": "nixos-configuration",
                "binding": "toplevel",
                "rules": [{
                    "field_name": "fail2banEnabled",
                    "description": "Brute-force protection must be enabled.",
                    "expression": "config.services.fail2ban.enable == true",
                    "strict": true
                }]
            }),
            compliance_metadata: json!({}),
            selected: false,
            order: 3,
        },
    ];

    let policies: Vec<XccdfPolicyExport> = entries
        .iter()
        .map(|entry| {
            let dependencies = json!([]);
            let digest = policy_digest(
                entry.name,
                Some(entry.description),
                entry.policy_type,
                "native",
                "nix-evaluation",
                &entry.config,
                &entry.compliance_metadata,
                &dependencies,
                Some(true),
            );
            XccdfPolicyExport {
                policy_id: entry.policy_id,
                policy_version_id: entry.policy_version_id,
                version: "1.0.0".into(),
                publication_state: PublicationState::Accepted,
                semantic_digest: digest,
                digest_algorithm: "sha-256".into(),
                canonicalization_version: "cf-model-json-1".into(),
                name: entry.name.into(),
                description: Some(entry.description.into()),
                policy_type: entry.policy_type.into(),
                execution_phase: "nix-evaluation".into(),
                implementation_state: entry.implementation_state,
                enabled_default: true,
                selected: entry.selected,
                policy_order: entry.order,
                config: entry.config.clone(),
                compliance_metadata: entry.compliance_metadata.clone(),
                dependencies,
                opaque_xml: None,
                source_mappings: vec![],
            }
        })
        .collect();

    let name = "Crystal Forge NixOS Baseline";
    let description = "Fixture bundle used to validate generated NixOS modules.";

    let mut members: Vec<(i32, BundleMembershipEntry)> = policies
        .iter()
        .map(|policy| {
            (
                policy.policy_order,
                BundleMembershipEntry {
                    policy_version_id: policy.policy_version_id,
                    selected: policy.selected,
                },
            )
        })
        .collect();
    members.sort_by_key(|(order, _)| *order);

    let bundle_digest = BundleVersionCanonical {
        name: name.into(),
        framework: "NIST SP 800-53".into(),
        framework_version: Some("5.1".into()),
        description: Some(description.into()),
        layer: "nixos".into(),
        owner: "crystal-forge".into(),
        members: members.into_iter().map(|(_, member)| member).collect(),
    }
    .compute_digest();

    let snapshot = XccdfBundleExport {
        bundle_id,
        bundle_version_id,
        version: "1".into(),
        publication_state: PublicationState::Accepted,
        semantic_digest: bundle_digest,
        digest_algorithm: "sha-256".into(),
        canonicalization_version: "cf-model-json-1".into(),
        name: name.into(),
        description: Some(description.into()),
        framework: "NIST SP 800-53".into(),
        framework_version: Some("5.1".into()),
        layer: "nixos".into(),
        owner: "crystal-forge".into(),
        groups: vec![],
        policies,
    };

    write_bundle_xccdf_export(&snapshot).expect("fixture bundle serializes")
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn policy_set_fixture_is_deterministic() {
        assert_eq!(policy_set_json(), policy_set_json());
    }

    #[test]
    fn bundle_fixture_is_deterministic() {
        assert_eq!(bundle_xccdf_xml(), bundle_xccdf_xml());
    }
}
