//! Domain model shared by the generator's layers.

use std::fmt;

use cf_compliance::xccdf::inference::NixosLiteralValue;
use uuid::Uuid;

/// Where a policy version came from.
///
/// The same immutable policy may appear in several input artifacts. Every
/// origin is retained in a sorted, deduplicated collection so that provenance
/// — and therefore generated bytes — never depends on the order the inputs
/// were given on the command line.
#[derive(Debug, Clone, PartialEq, Eq, Default)]
pub struct PolicyOrigin {
    /// Sorted labels of every input artifact this policy was read from.
    pub input_labels: Vec<String>,
    /// Sorted SHA-256 digests of every source artifact supplying this policy.
    pub source_sha256s: Vec<String>,
    /// Sorted bundle version IDs that selected this policy.
    pub bundle_version_ids: Vec<Uuid>,
}

impl PolicyOrigin {
    pub fn new(
        input_label: String,
        source_sha256: String,
        bundle_version_id: Option<Uuid>,
    ) -> Self {
        Self {
            input_labels: vec![input_label],
            source_sha256s: vec![source_sha256],
            bundle_version_ids: bundle_version_id.into_iter().collect(),
        }
    }

    /// Absorb another origin for the same immutable policy version.
    pub fn merge(&mut self, other: &Self) {
        self.input_labels.extend(other.input_labels.iter().cloned());
        self.source_sha256s
            .extend(other.source_sha256s.iter().cloned());
        self.bundle_version_ids
            .extend(other.bundle_version_ids.iter().copied());
        self.normalize();
    }

    fn normalize(&mut self) {
        self.input_labels.sort();
        self.input_labels.dedup();
        self.source_sha256s.sort();
        self.source_sha256s.dedup();
        self.bundle_version_ids.sort();
        self.bundle_version_ids.dedup();
    }

    /// A stable single label for diagnostics, independent of argument order.
    pub fn primary_input_label(&self) -> String {
        self.input_labels
            .first()
            .cloned()
            .unwrap_or_else(|| "<unknown>".to_string())
    }
}

/// One immutable policy version resolved from an input artifact.
///
/// Field names and defaults mirror the canonical Crystal Forge policy version
/// so that identity, digest, and eligibility decisions stay consistent with the
/// server.
#[derive(Debug, Clone)]
pub struct ResolvedPolicy {
    /// Portable lineage identity, stable across versions.
    pub policy_id: Uuid,
    /// Portable version identity, unique to this exact version.
    pub policy_version_id: Uuid,
    pub version: String,
    /// Lifecycle state proven by the export boundary.
    pub publication_state: String,
    pub name: String,
    pub description: Option<String>,
    pub policy_type: String,
    pub implementation_state: String,
    pub execution_phase: String,
    pub config: serde_json::Value,
    pub compliance_metadata: serde_json::Value,
    /// `cf-model-json-1` semantic digest, recomputed from the normalized fields.
    pub semantic_digest: String,
    pub origin: PolicyOrigin,
}

impl ResolvedPolicy {
    /// Stable human identity used in diagnostics and generated comments.
    pub fn label(&self) -> String {
        format!("{} @ {}", self.name, self.policy_version_id)
    }

    /// Compliance requirement identifiers preserved from the source export.
    ///
    /// These are metadata only and never affect generated configuration. A
    /// policy that maps to several requirements still emits one implementation.
    pub fn compliance_mappings(&self) -> Vec<String> {
        let mut mappings = Vec::new();

        if let Some(rule_id) = self
            .compliance_metadata
            .get("source_rule_id")
            .and_then(serde_json::Value::as_str)
        {
            mappings.push(format!("Source rule: {rule_id}"));
        }
        if let Some(stig_id) = self
            .compliance_metadata
            .get("stig_id")
            .and_then(serde_json::Value::as_str)
        {
            mappings.push(format!("STIG ID: {stig_id}"));
        }
        if let Some(severity) = self
            .compliance_metadata
            .get("severity")
            .and_then(serde_json::Value::as_str)
        {
            mappings.push(format!("Severity: {severity}"));
        }
        if let Some(identifiers) = self
            .compliance_metadata
            .get("identifiers")
            .and_then(serde_json::Value::as_array)
        {
            for identifier in identifiers {
                let system = identifier.get("system").and_then(serde_json::Value::as_str);
                let value = identifier.get("value").and_then(serde_json::Value::as_str);
                if let (Some(system), Some(value)) = (system, value) {
                    mappings.push(format!("{system}: {value}"));
                }
            }
        }

        // Deterministic and free of duplicates so generated comments and the
        // manifest are byte-stable.
        mappings.sort();
        mappings.dedup();
        mappings
    }
}

/// A bundle version export and the exact membership it froze.
#[derive(Debug, Clone)]
pub struct ResolvedBundle {
    pub bundle_id: Uuid,
    pub bundle_version_id: Uuid,
    pub name: String,
    pub version: String,
    pub framework: Option<String>,
    pub framework_version: Option<String>,
    pub publication_state: String,
    pub semantic_digest: Option<String>,
    /// Sorted digests of every source artifact that supplied this bundle version.
    pub source_sha256s: Vec<String>,
    /// Sorted labels of every input artifact that supplied this bundle version.
    pub input_labels: Vec<String>,
    /// Policy version IDs selected by this exact bundle version, in bundle order.
    pub selected_policy_version_ids: Vec<Uuid>,
}

impl ResolvedBundle {
    /// A stable single label for diagnostics, independent of argument order.
    pub fn primary_input_label(&self) -> String {
        self.input_labels
            .first()
            .cloned()
            .unwrap_or_else(|| "<unknown>".to_string())
    }

    /// Absorb another identical definition of this same bundle version.
    pub fn merge_origin(&mut self, other: &Self) {
        self.input_labels.extend(other.input_labels.iter().cloned());
        self.input_labels.sort();
        self.input_labels.dedup();
        self.source_sha256s
            .extend(other.source_sha256s.iter().cloned());
        self.source_sha256s.sort();
        self.source_sha256s.dedup();
    }
}

/// A single normalized NixOS option assignment.
///
/// This is the data-only representation the Nix layer consumes. The path is a
/// list of components rather than a dotted string, and the value is typed JSON
/// rather than Nix source text, so the generated module never evaluates
/// anything it reads from the manifest.
#[derive(Debug, Clone, PartialEq)]
pub struct OptionAssignment {
    /// NixOS option path components, for example
    /// `["services", "openssh", "settings", "PermitRootLogin"]`.
    pub path: Vec<String>,
    /// The assigned value as typed JSON (boolean, integer, string, list,
    /// object, or null).
    pub value: serde_json::Value,
}

impl OptionAssignment {
    /// Build an assignment from a dotted option path and a supported literal.
    ///
    /// The literal is converted to typed JSON here; no Nix source is produced.
    pub fn from_literal(option_path: &str, literal: &NixosLiteralValue) -> Self {
        Self {
            path: option_path.split('.').map(str::to_string).collect(),
            value: match literal {
                NixosLiteralValue::Boolean(value) => serde_json::Value::from(*value),
                NixosLiteralValue::Integer(value) => serde_json::Value::from(*value),
                NixosLiteralValue::StringLiteral(value) => serde_json::Value::String(value.clone()),
            },
        }
    }

    /// Dotted rendering of the path, for diagnostics and conflict messages.
    pub fn dotted_path(&self) -> String {
        self.path.join(".")
    }

    /// Compact JSON rendering of the value, for diagnostics.
    pub fn value_display(&self) -> String {
        serde_json::to_string(&self.value).unwrap_or_else(|_| "<unserializable>".to_string())
    }
}

/// Why a policy could not be converted into a NixOS module.
///
/// Every variant is reported explicitly; a skipped policy is never emitted as
/// though it were implemented.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum SkipReason {
    /// The policy is not a Crystal Forge-executable implementation.
    NotNative { implementation_state: String },
    /// The policy type has no declarative NixOS option representation.
    UnsupportedPolicyType { policy_type: String },
    /// An `any`-mode check does not determine a single configuration.
    AmbiguousRuleMode { mode: String },
    /// The policy carries no assertion expression at all.
    NoImplementation,
    /// An expression is not a plain `config.<path> == <literal>` assertion.
    UnrepresentableExpression { expression: String },
    /// The policy configuration is structurally invalid, so the policy cannot
    /// be converted in full. Never convert such a policy partially.
    MalformedConfig { detail: String },
    /// The policy assigns the same option two different values.
    SelfContradictory {
        option_path: String,
        first: String,
        second: String,
    },
}

impl SkipReason {
    /// Stable machine-readable code, used in the manifest.
    pub fn code(&self) -> &'static str {
        match self {
            Self::NotNative { .. } => "not_native",
            Self::UnsupportedPolicyType { .. } => "unsupported_policy_type",
            Self::AmbiguousRuleMode { .. } => "ambiguous_rule_mode",
            Self::NoImplementation => "no_implementation",
            Self::UnrepresentableExpression { .. } => "unrepresentable_expression",
            Self::MalformedConfig { .. } => "malformed_config",
            Self::SelfContradictory { .. } => "self_contradictory",
        }
    }
}

impl fmt::Display for SkipReason {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::NotNative {
                implementation_state,
            } => write!(
                f,
                "{implementation_state} policy has no NixOS implementation"
            ),
            Self::UnsupportedPolicyType { policy_type } => write!(
                f,
                "unsupported implementation type '{policy_type}' has no declarative NixOS representation"
            ),
            Self::AmbiguousRuleMode { mode } => write!(
                f,
                "rule mode '{mode}' does not determine a single NixOS configuration"
            ),
            Self::NoImplementation => {
                write!(f, "policy declares no assertion expression to convert")
            }
            Self::UnrepresentableExpression { expression } => write!(
                f,
                "expression is not a plain NixOS option assertion: {expression}"
            ),
            Self::MalformedConfig { detail } => {
                write!(f, "policy configuration is malformed: {detail}")
            }
            Self::SelfContradictory {
                option_path,
                first,
                second,
            } => write!(f, "policy assigns {option_path} both {first} and {second}"),
        }
    }
}

/// A policy that was reported rather than generated.
#[derive(Debug, Clone)]
pub struct SkippedPolicy {
    pub policy: ResolvedPolicy,
    pub reason: SkipReason,
}

/// A policy whose implementation was normalized into the manifest.
#[derive(Debug, Clone)]
pub struct GeneratedPolicy {
    pub policy: ResolvedPolicy,
    pub assignments: Vec<OptionAssignment>,
}

#[cfg(test)]
mod tests {
    use super::*;

    fn policy(compliance_metadata: serde_json::Value) -> ResolvedPolicy {
        ResolvedPolicy {
            policy_id: Uuid::nil(),
            policy_version_id: Uuid::nil(),
            version: "1".into(),
            publication_state: "accepted".into(),
            name: "p".into(),
            description: None,
            policy_type: "custom_check".into(),
            implementation_state: "native".into(),
            execution_phase: "nix-evaluation".into(),
            config: serde_json::json!({}),
            compliance_metadata,
            semantic_digest: String::new(),
            origin: PolicyOrigin::new("x".into(), String::new(), None),
        }
    }

    #[test]
    fn compliance_mappings_are_sorted_and_deduplicated() {
        let p = policy(serde_json::json!({
            "stig_id": "SV-230221r1",
            "severity": "high",
            "identifiers": [
                {"system": "http://cyber.mil/cci", "value": "CCI-000366"},
                {"system": "http://cyber.mil/cci", "value": "CCI-000366"},
                {"system": "NIST 800-53 Rev 5", "value": "IA-5"},
            ],
        }));
        let mappings = p.compliance_mappings();
        assert_eq!(
            mappings,
            vec![
                "NIST 800-53 Rev 5: IA-5".to_string(),
                "STIG ID: SV-230221r1".to_string(),
                "Severity: high".to_string(),
                "http://cyber.mil/cci: CCI-000366".to_string(),
            ]
        );
    }

    #[test]
    fn compliance_mappings_are_empty_without_metadata() {
        assert!(
            policy(serde_json::json!({}))
                .compliance_mappings()
                .is_empty()
        );
    }

    #[test]
    fn skip_reason_codes_are_stable() {
        assert_eq!(SkipReason::NoImplementation.code(), "no_implementation");
        assert_eq!(
            SkipReason::NotNative {
                implementation_state: "manual".into()
            }
            .code(),
            "not_native"
        );
    }

    #[test]
    fn manual_skip_reason_reads_like_the_documented_diagnostic() {
        let reason = SkipReason::NotNative {
            implementation_state: "manual".into(),
        };
        assert_eq!(
            reason.to_string(),
            "manual policy has no NixOS implementation"
        );
    }
}
