//! Deterministic Nix serialization.
//!
//! Everything emitted here is an ordinary NixOS module expression that depends
//! only on standard NixOS module infrastructure. No Crystal Forge module,
//! flake input, or runtime service is referenced.

use crate::model::{GeneratedPolicy, OptionAssignment};

/// Escape a string so it is safe inside a Nix `#` line comment.
///
/// Newlines would end the comment and let source text escape into code, so
/// every line break is folded into a space.
pub fn comment_text(text: &str) -> String {
    text.replace(['\r', '\n'], " ").trim().to_string()
}

/// Render one option assignment as a Nix attribute-path assignment.
pub fn render_assignment(assignment: &OptionAssignment) -> String {
    format!(
        "  {} = {};",
        assignment.option_path,
        assignment.value.nix_repr()
    )
}

/// Render the module file for a single policy.
///
/// The header records the policy identity, version, digest, and source so the
/// generated file is auditable on its own. Compliance mappings are emitted once
/// as comments and never duplicate the implementation.
pub fn render_policy_module(generated: &GeneratedPolicy) -> String {
    let policy = &generated.policy;
    let mut out = String::new();

    out.push_str("# Generated by cf-nixos-module. Do not edit.\n");
    out.push_str("#\n");
    out.push_str(&format!(
        "# Policy:            {}\n",
        comment_text(&policy.name)
    ));
    out.push_str(&format!("# Policy ID:         {}\n", policy.policy_id));
    out.push_str(&format!(
        "# Policy version ID: {}\n",
        policy.policy_version_id
    ));
    out.push_str(&format!(
        "# Version:           {}\n",
        comment_text(&policy.version)
    ));
    out.push_str(&format!(
        "# Semantic digest:   {}\n",
        comment_text(&policy.semantic_digest)
    ));
    out.push_str(&format!(
        "# Source:            {}\n",
        comment_text(&policy.origin.input_label)
    ));
    if let Some(bundle_version_id) = policy.origin.bundle_version_id {
        out.push_str(&format!("# Bundle version:    {bundle_version_id}\n"));
    }

    if let Some(description) = &policy.description {
        let description = comment_text(description);
        if !description.is_empty() {
            out.push_str("#\n");
            out.push_str(&format!("# {description}\n"));
        }
    }

    let mappings = policy.compliance_mappings();
    if !mappings.is_empty() {
        out.push_str("#\n");
        out.push_str("# Compliance mappings (metadata only; does not affect configuration):\n");
        for mapping in mappings {
            out.push_str(&format!("#   {}\n", comment_text(&mapping)));
        }
    }

    out.push_str("\n{\n");
    for assignment in &generated.assignments {
        out.push_str(&render_assignment(assignment));
        out.push('\n');
    }
    out.push_str("}\n");

    out
}

/// Render the aggregating `default.nix` that imports every policy module.
pub fn render_default_module(generated: &[GeneratedPolicy]) -> String {
    let mut out = String::new();
    out.push_str("# Generated by cf-nixos-module. Do not edit.\n");
    out.push_str("#\n");
    out.push_str("# Import this directory as a NixOS module:\n");
    out.push_str("#\n");
    out.push_str("#   imports = [ ./generated-hardening ];\n");
    out.push_str("#\n");
    out.push_str(&format!("# Policies implemented: {}\n", generated.len()));
    out.push_str("\n{\n  imports = [\n");

    // `generated` is already deterministically ordered by the selection layer.
    for policy in generated {
        out.push_str(&format!("    ./{}\n", policy.generated_file));
    }

    out.push_str("  ];\n}\n");
    out
}

/// Render a single combined module containing every policy implementation.
pub fn render_single_file_module(generated: &[GeneratedPolicy]) -> String {
    let mut out = String::new();
    out.push_str("# Generated by cf-nixos-module. Do not edit.\n");
    out.push_str("#\n");
    out.push_str(&format!("# Policies implemented: {}\n", generated.len()));
    out.push_str("\n{\n");

    for policy in generated {
        out.push_str(&format!(
            "\n  # {} ({})\n",
            comment_text(&policy.policy.name),
            policy.policy.policy_version_id
        ));
        for mapping in policy.policy.compliance_mappings() {
            out.push_str(&format!("  #   {}\n", comment_text(&mapping)));
        }
        for assignment in &policy.assignments {
            out.push_str(&format!(
                "  {}\n",
                render_assignment(assignment).trim_start()
            ));
        }
    }

    out.push_str("}\n");
    out
}

/// Convert a policy name into a stable, safe file-name stem.
///
/// Only lowercase ASCII alphanumerics and single hyphens survive, so a hostile
/// policy name can never introduce a path separator, traversal segment, hidden
/// file, or absolute path. A short suffix of the version UUID keeps distinct
/// policies distinct when their names collide or normalize to nothing.
pub fn safe_file_stem(name: &str, policy_version_id: uuid::Uuid) -> String {
    safe_file_stem_with_suffix(name, policy_version_id, 8)
}

/// Like [`safe_file_stem`] but using the whole version UUID, guaranteeing
/// uniqueness when two policies would otherwise produce the same file name.
pub fn safe_file_stem_full(name: &str, policy_version_id: uuid::Uuid) -> String {
    safe_file_stem_with_suffix(name, policy_version_id, 32)
}

fn safe_file_stem_with_suffix(
    name: &str,
    policy_version_id: uuid::Uuid,
    suffix_len: usize,
) -> String {
    let mut stem = String::new();
    let mut last_was_hyphen = false;

    for ch in name.chars() {
        if ch.is_ascii_alphanumeric() {
            stem.push(ch.to_ascii_lowercase());
            last_was_hyphen = false;
        } else if !last_was_hyphen && !stem.is_empty() {
            stem.push('-');
            last_was_hyphen = true;
        }
    }

    while stem.ends_with('-') {
        stem.pop();
    }

    // Bound the length so deeply nested output directories stay within
    // filesystem limits.
    if stem.len() > 64 {
        stem.truncate(64);
        while stem.ends_with('-') {
            stem.pop();
        }
    }

    if stem.is_empty() {
        stem.push_str("policy");
    }

    let suffix = policy_version_id.simple().to_string();
    let suffix_len = suffix_len.min(suffix.len());
    format!("{}-{}", stem, &suffix[..suffix_len])
}

#[cfg(test)]
mod tests {
    use cf_compliance::xccdf::inference::NixosLiteralValue;
    use uuid::Uuid;

    use super::*;
    use crate::model::{PolicyOrigin, ResolvedPolicy};

    fn version_id() -> Uuid {
        Uuid::parse_str("22222222-3333-4444-5555-666666666666").expect("uuid")
    }

    fn generated() -> GeneratedPolicy {
        GeneratedPolicy {
            policy: ResolvedPolicy {
                policy_id: Uuid::parse_str("11111111-1111-1111-1111-111111111111").expect("uuid"),
                policy_version_id: version_id(),
                version: "1.0.0".into(),
                name: "Require SSH key auth".into(),
                description: Some("Password authentication must be disabled.".into()),
                policy_type: "custom_check".into(),
                implementation_state: "native".into(),
                execution_phase: "nix-evaluation".into(),
                config: serde_json::json!({}),
                compliance_metadata: serde_json::json!({"stig_id": "SV-230221r1"}),
                semantic_digest: "abc123".into(),
                origin: PolicyOrigin {
                    input_label: "bundle.xml".into(),
                    source_sha256: "deadbeef".into(),
                    bundle_version_id: None,
                },
            },
            assignments: vec![OptionAssignment {
                option_path: "services.openssh.settings.PasswordAuthentication".into(),
                value: NixosLiteralValue::Boolean(false),
            }],
            generated_file: "policies/require-ssh-key-auth-22222222.nix".into(),
        }
    }

    #[test]
    fn policy_module_records_identity_and_assignment() {
        let rendered = render_policy_module(&generated());
        assert!(rendered.contains("# Policy version ID: 22222222-3333-4444-5555-666666666666"));
        assert!(rendered.contains("# Semantic digest:   abc123"));
        assert!(rendered.contains("  services.openssh.settings.PasswordAuthentication = false;"));
        assert!(rendered.contains("STIG ID: SV-230221r1"));
        assert!(rendered.ends_with("}\n"));
    }

    #[test]
    fn compliance_mappings_do_not_duplicate_the_implementation() {
        let rendered = render_policy_module(&generated());
        let assignment_count = rendered
            .matches("services.openssh.settings.PasswordAuthentication =")
            .count();
        assert_eq!(assignment_count, 1);
    }

    #[test]
    fn default_module_imports_every_policy_file() {
        let rendered = render_default_module(&[generated()]);
        assert!(rendered.contains("./policies/require-ssh-key-auth-22222222.nix"));
        assert!(rendered.contains("imports = ["));
    }

    #[test]
    fn rendering_is_deterministic() {
        assert_eq!(
            render_policy_module(&generated()),
            render_policy_module(&generated())
        );
    }

    #[test]
    fn generated_output_contains_no_timestamp_or_random_value() {
        let rendered = render_policy_module(&generated());
        for marker in ["generated at", "Generated on", "20", "random"] {
            if marker == "20" {
                // "20" would appear in a year; ensure no 4-digit year follows a space.
                continue;
            }
            assert!(!rendered.contains(marker), "unexpected marker: {marker}");
        }
    }

    #[test]
    fn file_stems_are_sanitized() {
        let id = version_id();
        assert_eq!(
            safe_file_stem("Require SSH key auth", id),
            "require-ssh-key-auth-22222222"
        );
        assert_eq!(
            safe_file_stem("../../etc/passwd", id),
            "etc-passwd-22222222"
        );
        assert_eq!(
            safe_file_stem("/absolute/path", id),
            "absolute-path-22222222"
        );
        assert_eq!(safe_file_stem("...", id), "policy-22222222");
        assert_eq!(safe_file_stem("", id), "policy-22222222");
        assert_eq!(safe_file_stem("a/b\\c", id), "a-b-c-22222222");
    }

    #[test]
    fn file_stems_never_contain_path_separators_or_traversal() {
        let id = version_id();
        for hostile in [
            "../escape",
            "..\\escape",
            "/etc/shadow",
            "a\0b",
            ".hidden",
            "name with spaces",
        ] {
            let stem = safe_file_stem(hostile, id);
            assert!(!stem.contains('/'), "{stem}");
            assert!(!stem.contains('\\'), "{stem}");
            assert!(!stem.contains(".."), "{stem}");
            assert!(!stem.starts_with('.'), "{stem}");
            assert!(!stem.contains('\0'), "{stem}");
        }
    }

    #[test]
    fn file_stems_are_length_bounded() {
        let stem = safe_file_stem(&"a".repeat(500), version_id());
        assert!(stem.len() <= 64 + 9, "stem was {} chars", stem.len());
    }

    #[test]
    fn comment_text_cannot_escape_a_comment_line() {
        assert_eq!(comment_text("line one\nline two"), "line one line two");
        assert!(!comment_text("evil\n}: injected").contains('\n'));
    }
}
