//! The small amount of Nix source the generator emits.
//!
//! The generated artifact is deliberately tiny: a generic library function, a
//! `default.nix` that wires it to `manifest.json`, and the manifest itself. No
//! per-policy Nix file is generated, because every policy's implementation is
//! already normalized data in the manifest.

/// The generic compliance module factory, embedded at build time.
///
/// This is the exact same file the repository exposes as
/// `lib.crystal-forge.mkComplianceModule`, so the helper that is unit-tested in
/// `checks/compliance-module` and the helper shipped inside every generated
/// artifact cannot drift apart.
pub const COMPLIANCE_LIB_NIX: &str = include_str!("../nix/mk-compliance-module.nix");

/// File name of the embedded generic library inside the generated artifact.
pub const LIB_FILE: &str = "lib.nix";

/// Render the generated `default.nix`.
///
/// It reads `manifest.json` as data and hands it to the generic factory.
/// `builtins.fromJSON` here decodes data only: no value from the manifest is
/// ever evaluated as Nix source.
pub fn render_default_module(baseline: &str, policy_count: usize, skipped_count: usize) -> String {
    format!(
        r##"# Generated by cf-nixos-module. Do not edit.
#
# Standalone Crystal Forge compliance baseline: {baseline}
#
# Usage:
#
#   {{
#     imports = [ ./generated-compliance ];
#     # Applied by default; disable explicitly when needed:
#     crystal-forge.compliance.{baseline}.enable = false;
#   }}
#
# Importing this directory applies the baseline by default. Set the enable
# option above to false to disable it explicitly.
#
# Policies implemented: {policy_count}
# Policies reported as unconvertible: {skipped_count}
#
# Crystal Forge validated and resolved this content before generation. The Nix
# code here only turns normalized `path + typed value` data from manifest.json
# into NixOS option definitions; it never evaluates policy source.
{{config, lib, ...}}:
import ./{LIB_FILE} {{
  inherit config lib;
  manifest = builtins.fromJSON (builtins.readFile ./manifest.json);
  baseline = "{baseline}";
}}
"##
    )
}

/// Derive a stable, Nix-safe baseline identifier from a display name.
///
/// The result is a lowercase, hyphen-separated identifier that is always a
/// valid unquoted Nix attribute name: it never starts with a digit or hyphen
/// and is never empty.
pub fn sanitize_baseline_name(name: &str) -> String {
    let mut identifier = String::new();
    let mut last_was_hyphen = false;

    for ch in name.chars() {
        if ch.is_ascii_alphanumeric() {
            identifier.push(ch.to_ascii_lowercase());
            last_was_hyphen = false;
        } else if !identifier.is_empty() && !last_was_hyphen {
            identifier.push('-');
            last_was_hyphen = true;
        }
    }

    while identifier.ends_with('-') {
        identifier.pop();
    }

    if identifier.len() > 64 {
        identifier.truncate(64);
        while identifier.ends_with('-') {
            identifier.pop();
        }
    }

    // A Nix identifier may not begin with a digit.
    if identifier
        .chars()
        .next()
        .is_some_and(|ch| ch.is_ascii_digit())
    {
        identifier.insert(0, 'b');
    }

    if identifier.is_empty() {
        identifier.push_str("baseline");
    }

    identifier
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn embedded_library_is_the_repository_library() {
        // Guards against the embedded copy silently diverging in content.
        assert!(
            COMPLIANCE_LIB_NIX.contains("mkComplianceModule")
                || COMPLIANCE_LIB_NIX.contains("crystal-forge.compliance")
        );
        assert!(COMPLIANCE_LIB_NIX.contains("setAttrByPath"));
        // The library must never evaluate manifest content as Nix source.
        assert!(!COMPLIANCE_LIB_NIX.contains("import ("));
        assert!(!COMPLIANCE_LIB_NIX.contains("fromJSON"));
    }

    #[test]
    fn default_module_wires_the_manifest_to_the_library() {
        let rendered = render_default_module("production-baseline", 4, 3);
        assert!(rendered.contains("import ./lib.nix"));
        assert!(rendered.contains("builtins.fromJSON (builtins.readFile ./manifest.json)"));
        assert!(rendered.contains(r#"baseline = "production-baseline";"#));
        assert!(rendered.contains("crystal-forge.compliance.production-baseline.enable = false;"));
    }

    #[test]
    fn default_module_is_deterministic() {
        assert_eq!(
            render_default_module("b", 1, 0),
            render_default_module("b", 1, 0)
        );
    }

    #[test]
    fn baseline_names_are_sanitized() {
        assert_eq!(
            sanitize_baseline_name("Production Baseline"),
            "production-baseline"
        );
        assert_eq!(
            sanitize_baseline_name("production-baseline.json"),
            "production-baseline-json"
        );
        assert_eq!(
            sanitize_baseline_name("DISA NixOS STIG V1R1"),
            "disa-nixos-stig-v1r1"
        );
        assert_eq!(sanitize_baseline_name(""), "baseline");
        assert_eq!(sanitize_baseline_name("..."), "baseline");
        assert_eq!(sanitize_baseline_name("2024-baseline"), "b2024-baseline");
    }

    #[test]
    fn baseline_names_are_valid_nix_identifiers() {
        for input in [
            "a/b",
            "../escape",
            "with spaces",
            "Ünïcödé",
            "9lives",
            "-leading",
            "trailing-",
            &"x".repeat(500),
        ] {
            let identifier = sanitize_baseline_name(input);
            assert!(!identifier.is_empty(), "empty for {input:?}");
            assert!(
                !identifier.starts_with(|c: char| c.is_ascii_digit()),
                "{identifier} starts with a digit"
            );
            assert!(!identifier.starts_with('-'), "{identifier}");
            assert!(!identifier.ends_with('-'), "{identifier}");
            assert!(
                identifier
                    .chars()
                    .all(|c| c.is_ascii_lowercase() || c.is_ascii_digit() || c == '-'),
                "{identifier} has invalid characters"
            );
        }
    }
}
