//! Mock data for systems views.
//!
//! Provides test data for development and testing.

use chrono::{Duration, TimeZone, Utc};
use dioxus::prelude::*;
use uuid::Uuid;

use crate::api::models::{
    CveSummary, DeploymentStatus, FlakeSummary, HealthStatus, PipelineStage, SystemDetail,
    SystemHardwareInfo, SystemNetworkInfo, SystemSecurityInfo,
};

#[path = "systems_mock_data_extra.rs"]
mod systems_mock_data_extra;

pub fn mock_system_detail_by_id(id: &str) -> Option<SystemDetail> {
    let parsed = Uuid::parse_str(id).ok()?;
    mock_system_details()
        .into_iter()
        .find(|system| system.id == parsed)
}

pub fn mock_system_details() -> Vec<SystemDetail> {
    let base_time = Utc.with_ymd_and_hms(2026, 2, 8, 15, 19, 29).unwrap();
    let flake_core = FlakeSummary {
        id: 1,
        name: "infrastructure".to_string(),
        repo_url: "github:acme/infra".to_string(),
        latest_commit: Some("a1b2c3d".to_string()),
    };
    let flake_staging = FlakeSummary {
        id: 2,
        name: "edge-nodes".to_string(),
        repo_url: "github:acme/edge".to_string(),
        latest_commit: Some("1234567".to_string()),
    };
    let flake_dev = FlakeSummary {
        id: 3,
        name: "workstations".to_string(),
        repo_url: "github:acme/workstations".to_string(),
        latest_commit: Some("f1a2b3c".to_string()),
    };

    let mut systems = vec![
        build_system_detail(
            base_time,
            1,
            "atlas-01",
            "production",
            "10.42.1.11",
            "c8:7f:54:5d:ae:11",
            "10.42.1.1",
            HealthStatus::Healthy,
            DeploymentStatus::UpToDate,
            Some(PipelineStage::BuildComplete),
            "24.11",
            "6.12.66",
            "Immediate",
            "0.2.1",
            "m6wc1njr09pbpv49q60c1",
            "AMD EPYC 7543P 32-Core Processor",
            32,
            128.0,
            177_536,
            "ATLAS-01-BRD",
            "2.5.4",
            true,
            true,
            false,
            Some("enforcing"),
            CveSummary {
                critical: 0,
                high: 1,
                medium: 4,
                low: 12,
            },
            Some(flake_core.clone()),
            2,
        ),
        build_system_detail(
            base_time,
            2,
            "atlas-02",
            "production",
            "10.42.1.12",
            "c8:7f:54:5d:ae:12",
            "10.42.1.1",
            HealthStatus::Healthy,
            DeploymentStatus::UpToDate,
            Some(PipelineStage::ReadyForDeploy),
            "24.11",
            "6.12.66",
            "Immediate",
            "0.2.1",
            "b51f0bb7e6b58b4b9c84",
            "AMD EPYC 7713 64-Core Processor",
            64,
            256.0,
            202_415,
            "ATLAS-02-BRD",
            "2.6.1",
            true,
            true,
            false,
            Some("enforcing"),
            CveSummary {
                critical: 0,
                high: 2,
                medium: 5,
                low: 10,
            },
            Some(flake_core.clone()),
            1,
        ),
        build_system_detail(
            base_time,
            3,
            "atlas-03",
            "production",
            "10.42.1.13",
            "c8:7f:54:5d:ae:13",
            "10.42.1.1",
            HealthStatus::Healthy,
            DeploymentStatus::UpToDate,
            Some(PipelineStage::BuildComplete),
            "24.11",
            "6.12.66",
            "Immediate",
            "0.2.0",
            "d9029ab7c4ff9811b0ff",
            "Intel Xeon Gold 6338",
            32,
            192.0,
            154_022,
            "ATLAS-03-BRD",
            "2.4.9",
            true,
            true,
            false,
            Some("enforcing"),
            CveSummary {
                critical: 0,
                high: 1,
                medium: 3,
                low: 8,
            },
            Some(flake_core.clone()),
            4,
        ),
        build_system_detail(
            base_time,
            4,
            "atlas-04",
            "production",
            "10.42.1.14",
            "c8:7f:54:5d:ae:14",
            "10.42.1.1",
            HealthStatus::Healthy,
            DeploymentStatus::NeverDeployed,
            Some(PipelineStage::ReadyForBuild),
            "24.11",
            "6.12.60",
            "Immediate",
            "0.2.1",
            "c7ce0b0b05a99e6d7d4e",
            "Intel Xeon Silver 4310",
            24,
            96.0,
            88_450,
            "ATLAS-04-BRD",
            "2.4.7",
            true,
            false,
            false,
            Some("permissive"),
            CveSummary {
                critical: 0,
                high: 1,
                medium: 2,
                low: 6,
            },
            Some(flake_core.clone()),
            6,
        ),
        build_system_detail(
            base_time,
            5,
            "atlas-05",
            "production",
            "10.42.1.15",
            "c8:7f:54:5d:ae:15",
            "10.42.1.1",
            HealthStatus::Healthy,
            DeploymentStatus::NeverDeployed,
            Some(PipelineStage::DryRun),
            "24.11",
            "6.12.60",
            "Immediate",
            "0.2.0",
            "03d23b17c1d80c7e3f62",
            "AMD EPYC 7302P 16-Core Processor",
            16,
            64.0,
            91_007,
            "ATLAS-05-BRD",
            "2.4.7",
            false,
            false,
            false,
            Some("disabled"),
            CveSummary {
                critical: 0,
                high: 0,
                medium: 2,
                low: 5,
            },
            Some(flake_core.clone()),
            8,
        ),
        build_system_detail(
            base_time,
            6,
            "luna-01",
            "staging",
            "10.42.2.21",
            "b8:5f:f7:1a:22:21",
            "10.42.2.1",
            HealthStatus::Healthy,
            DeploymentStatus::UpToDate,
            Some(PipelineStage::ReadyForDeploy),
            "24.05",
            "6.9.12",
            "Immediate",
            "0.2.1",
            "a11c209f7b0b1a9c437f",
            "AMD Ryzen 9 5950X 16-Core Processor",
            16,
            64.0,
            72_340,
            "LUNA-01-BRD",
            "1.9.2",
            true,
            false,
            false,
            Some("enforcing"),
            CveSummary {
                critical: 0,
                high: 1,
                medium: 3,
                low: 7,
            },
            Some(flake_staging.clone()),
            3,
        ),
        build_system_detail(
            base_time,
            7,
            "luna-02",
            "staging",
            "10.42.2.22",
            "b8:5f:f7:1a:22:22",
            "10.42.2.1",
            HealthStatus::Warning,
            DeploymentStatus::NeverDeployed,
            Some(PipelineStage::ReadyForBuild),
            "24.05",
            "6.9.12",
            "Boot Only",
            "0.2.0",
            "7a2f0b12e117a3db3f2a",
            "AMD Ryzen 9 5900X 12-Core Processor",
            12,
            48.0,
            39_210,
            "LUNA-02-BRD",
            "1.8.8",
            true,
            false,
            false,
            Some("enforcing"),
            CveSummary {
                critical: 1,
                high: 2,
                medium: 4,
                low: 8,
            },
            Some(flake_staging.clone()),
            12,
        ),
        build_system_detail(
            base_time,
            8,
            "orion-01",
            "production",
            "10.42.1.31",
            "c8:7f:54:5d:ae:31",
            "10.42.1.1",
            HealthStatus::Healthy,
            DeploymentStatus::UpToDate,
            Some(PipelineStage::BuildComplete),
            "24.11",
            "6.12.66",
            "Immediate",
            "0.2.1",
            "24ed117db226b5f87520",
            "AMD EPYC 75F3 32-Core Processor",
            32,
            128.0,
            132_996,
            "ORION-01-BRD",
            "2.6.0",
            true,
            true,
            false,
            Some("enforcing"),
            CveSummary {
                critical: 0,
                high: 1,
                medium: 3,
                low: 6,
            },
            Some(flake_core.clone()),
            1,
        ),
    ];

    systems.extend(systems_mock_data_extra::additional_systems(
        base_time,
        &flake_core,
        &flake_staging,
        &flake_dev,
    ));

    systems
}

pub(super) fn build_system_detail(
    base_time: chrono::DateTime<Utc>,
    id: u128,
    hostname: &str,
    environment: &str,
    primary_ip: &str,
    primary_mac: &str,
    gateway_ip: &str,
    health_status: HealthStatus,
    deployment_status: DeploymentStatus,
    pipeline_stage: Option<PipelineStage>,
    nixos_version: &str,
    kernel: &str,
    deployment_policy: &str,
    agent_version: &str,
    store_hash: &str,
    cpu_brand: &str,
    cpu_cores: i32,
    memory_gb: f64,
    uptime_secs: i64,
    board_serial: &str,
    bios_version: &str,
    tpm_present: bool,
    secure_boot_enabled: bool,
    fips_mode: bool,
    selinux_status: Option<&str>,
    cve_counts: CveSummary,
    flake: Option<FlakeSummary>,
    last_seen_offset_hours: i64,
) -> SystemDetail {
    let last_seen = base_time - Duration::hours(last_seen_offset_hours);
    let is_active = !matches!(health_status, HealthStatus::Offline);
    let store_path = if matches!(deployment_status, DeploymentStatus::Unknown) {
        None
    } else {
        Some(format!(
            "/nix/store/{store_hash}-nixos-system-{hostname}-{nixos_version}"
        ))
    };

    SystemDetail {
        id: Uuid::from_u128(id),
        hostname: hostname.to_string(),
        system_configuration_name: None,
        environment: Some(environment.to_string()),
        is_active,
        deployment_policy: deployment_policy.to_string(),
        health_status,
        deployment_status,
        pipeline_stage,
        nixos_version: Some(nixos_version.to_string()),
        kernel: Some(kernel.to_string()),
        agent_version: Some(agent_version.to_string()),
        current_store_path: store_path,
        hardware: SystemHardwareInfo {
            cpu_brand: Some(cpu_brand.to_string()),
            cpu_cores: Some(cpu_cores),
            memory_gb: Some(memory_gb),
            uptime_secs: Some(uptime_secs),
            board_serial: Some(board_serial.to_string()),
            bios_version: Some(bios_version.to_string()),
        },
        network: SystemNetworkInfo {
            primary_ip: Some(primary_ip.to_string()),
            primary_mac: Some(primary_mac.to_string()),
            gateway_ip: Some(gateway_ip.to_string()),
        },
        security: SystemSecurityInfo {
            tpm_present: Some(tpm_present),
            secure_boot_enabled: Some(secure_boot_enabled),
            fips_mode: Some(fips_mode),
            selinux_status: selinux_status.map(|value| value.to_string()),
        },
        cve_counts,
        flake,
        last_seen: Some(last_seen),
        created_at: base_time - Duration::days(420),
        updated_at: base_time - Duration::hours(1),
    }
}
