//! Mock data for systems views.
//!
//! Provides test data for development and testing.

use chrono::{Duration, TimeZone, Utc};
use dioxus::prelude::*;
use uuid::Uuid;

use crate::api::models::{
    CveSummary, DeploymentStatus, FlakeSummary, HealthStatus, PipelineStage, SystemDetail,
    SystemHardwareInfo, SystemNetworkInfo, SystemSecurityInfo,
};

pub fn mock_system_detail_by_id(id: &str) -> Option<SystemDetail> {
    let parsed = Uuid::parse_str(id).ok()?;
    mock_system_details()
        .into_iter()
        .find(|system| system.id == parsed)
}

pub fn mock_system_details() -> Vec<SystemDetail> {
    let base_time = Utc.with_ymd_and_hms(2026, 2, 8, 15, 19, 29).unwrap();
    let flake_core = FlakeSummary {
        id: 1,
        name: "infrastructure".to_string(),
        repo_url: "github:acme/infra".to_string(),
        latest_commit: Some("a1b2c3d".to_string()),
    };
    let flake_staging = FlakeSummary {
        id: 2,
        name: "edge-nodes".to_string(),
        repo_url: "github:acme/edge".to_string(),
        latest_commit: Some("1234567".to_string()),
    };
    let flake_dev = FlakeSummary {
        id: 3,
        name: "workstations".to_string(),
        repo_url: "github:acme/workstations".to_string(),
        latest_commit: Some("f1a2b3c".to_string()),
    };

    vec![
        build_system_detail(
            base_time,
            1,
            "atlas-01",
            "production",
            "10.42.1.11",
            "c8:7f:54:5d:ae:11",
            "10.42.1.1",
            HealthStatus::Healthy,
            DeploymentStatus::UpToDate,
            Some(PipelineStage::BuildComplete),
            "24.11",
            "6.12.66",
            "Immediate",
            "0.2.1",
            "m6wc1njr09pbpv49q60c1",
            "AMD EPYC 7543P 32-Core Processor",
            32,
            128.0,
            177_536,
            "ATLAS-01-BRD",
            "2.5.4",
            true,
            true,
            false,
            Some("enforcing"),
            CveSummary {
                critical: 0,
                high: 1,
                medium: 4,
                low: 12,
            },
            Some(flake_core.clone()),
            2,
        ),
        build_system_detail(
            base_time,
            2,
            "atlas-02",
            "production",
            "10.42.1.12",
            "c8:7f:54:5d:ae:12",
            "10.42.1.1",
            HealthStatus::Healthy,
            DeploymentStatus::UpToDate,
            Some(PipelineStage::ReadyForDeploy),
            "24.11",
            "6.12.66",
            "Immediate",
            "0.2.1",
            "b51f0bb7e6b58b4b9c84",
            "AMD EPYC 7713 64-Core Processor",
            64,
            256.0,
            202_415,
            "ATLAS-02-BRD",
            "2.6.1",
            true,
            true,
            false,
            Some("enforcing"),
            CveSummary {
                critical: 0,
                high: 2,
                medium: 5,
                low: 10,
            },
            Some(flake_core.clone()),
            1,
        ),
        build_system_detail(
            base_time,
            3,
            "atlas-03",
            "production",
            "10.42.1.13",
            "c8:7f:54:5d:ae:13",
            "10.42.1.1",
            HealthStatus::Healthy,
            DeploymentStatus::UpToDate,
            Some(PipelineStage::BuildComplete),
            "24.11",
            "6.12.66",
            "Immediate",
            "0.2.0",
            "d9029ab7c4ff9811b0ff",
            "Intel Xeon Gold 6338",
            32,
            192.0,
            154_022,
            "ATLAS-03-BRD",
            "2.4.9",
            true,
            true,
            false,
            Some("enforcing"),
            CveSummary {
                critical: 0,
                high: 1,
                medium: 3,
                low: 8,
            },
            Some(flake_core.clone()),
            4,
        ),
        build_system_detail(
            base_time,
            4,
            "atlas-04",
            "production",
            "10.42.1.14",
            "c8:7f:54:5d:ae:14",
            "10.42.1.1",
            HealthStatus::Healthy,
            DeploymentStatus::NeverDeployed,
            Some(PipelineStage::ReadyForBuild),
            "24.11",
            "6.12.60",
            "Immediate",
            "0.2.1",
            "c7ce0b0b05a99e6d7d4e",
            "Intel Xeon Silver 4310",
            24,
            96.0,
            88_450,
            "ATLAS-04-BRD",
            "2.4.7",
            true,
            false,
            false,
            Some("permissive"),
            CveSummary {
                critical: 0,
                high: 1,
                medium: 2,
                low: 6,
            },
            Some(flake_core.clone()),
            6,
        ),
        build_system_detail(
            base_time,
            5,
            "atlas-05",
            "production",
            "10.42.1.15",
            "c8:7f:54:5d:ae:15",
            "10.42.1.1",
            HealthStatus::Healthy,
            DeploymentStatus::NeverDeployed,
            Some(PipelineStage::DryRun),
            "24.11",
            "6.12.60",
            "Immediate",
            "0.2.0",
            "03d23b17c1d80c7e3f62",
            "AMD EPYC 7302P 16-Core Processor",
            16,
            64.0,
            91_007,
            "ATLAS-05-BRD",
            "2.4.7",
            false,
            false,
            false,
            Some("disabled"),
            CveSummary {
                critical: 0,
                high: 0,
                medium: 2,
                low: 5,
            },
            Some(flake_core.clone()),
            8,
        ),
        build_system_detail(
            base_time,
            6,
            "luna-01",
            "staging",
            "10.42.2.21",
            "b8:5f:f7:1a:22:21",
            "10.42.2.1",
            HealthStatus::Healthy,
            DeploymentStatus::UpToDate,
            Some(PipelineStage::ReadyForDeploy),
            "24.05",
            "6.9.12",
            "Immediate",
            "0.2.1",
            "a11c209f7b0b1a9c437f",
            "AMD Ryzen 9 5950X 16-Core Processor",
            16,
            64.0,
            72_340,
            "LUNA-01-BRD",
            "1.9.2",
            true,
            false,
            false,
            Some("enforcing"),
            CveSummary {
                critical: 0,
                high: 1,
                medium: 3,
                low: 7,
            },
            Some(flake_staging.clone()),
            3,
        ),
        build_system_detail(
            base_time,
            7,
            "luna-02",
            "staging",
            "10.42.2.22",
            "b8:5f:f7:1a:22:22",
            "10.42.2.1",
            HealthStatus::Warning,
            DeploymentStatus::NeverDeployed,
            Some(PipelineStage::ReadyForBuild),
            "24.05",
            "6.9.12",
            "Boot Only",
            "0.2.0",
            "7a2f0b12e117a3db3f2a",
            "AMD Ryzen 9 5900X 12-Core Processor",
            12,
            48.0,
            39_210,
            "LUNA-02-BRD",
            "1.8.8",
            true,
            false,
            false,
            Some("enforcing"),
            CveSummary {
                critical: 1,
                high: 2,
                medium: 4,
                low: 8,
            },
            Some(flake_staging.clone()),
            12,
        ),
        build_system_detail(
            base_time,
            8,
            "orion-01",
            "production",
            "10.42.1.31",
            "c8:7f:54:5d:ae:31",
            "10.42.1.1",
            HealthStatus::Healthy,
            DeploymentStatus::UpToDate,
            Some(PipelineStage::BuildComplete),
            "24.11",
            "6.12.66",
            "Immediate",
            "0.2.1",
            "24ed117db226b5f87520",
            "AMD EPYC 75F3 32-Core Processor",
            32,
            128.0,
            132_996,
            "ORION-01-BRD",
            "2.6.0",
            true,
            true,
            false,
            Some("enforcing"),
            CveSummary {
                critical: 0,
                high: 1,
                medium: 3,
                low: 6,
            },
            Some(flake_core.clone()),
            1,
        ),
        build_system_detail(
            base_time,
            9,
            "ws-001",
            "development",
            "10.42.3.11",
            "e8:2f:2a:44:11:01",
            "10.42.3.1",
            HealthStatus::Healthy,
            DeploymentStatus::Behind,
            Some(PipelineStage::BuildComplete),
            "24.05",
            "6.9.12",
            "Manual",
            "0.2.1",
            "d10c01f3fda6b36b845e",
            "AMD Ryzen 7 5800X 8-Core Processor",
            8,
            32.0,
            54_210,
            "WS-001-BRD",
            "1.3.1",
            false,
            false,
            false,
            Some("disabled"),
            CveSummary {
                critical: 0,
                high: 1,
                medium: 2,
                low: 4,
            },
            Some(flake_dev.clone()),
            2,
        ),
        build_system_detail(
            base_time,
            10,
            "ws-002",
            "development",
            "10.42.3.12",
            "e8:2f:2a:44:11:02",
            "10.42.3.1",
            HealthStatus::Healthy,
            DeploymentStatus::NeverDeployed,
            Some(PipelineStage::ReadyForBuild),
            "24.05",
            "6.9.12",
            "Boot Only",
            "0.2.0",
            "f21b209f2a44d19abce9",
            "Intel Core i7-12700 12-Core Processor",
            12,
            32.0,
            29_300,
            "WS-002-BRD",
            "1.2.8",
            false,
            false,
            false,
            None,
            CveSummary {
                critical: 0,
                high: 0,
                medium: 2,
                low: 3,
            },
            Some(flake_dev.clone()),
            5,
        ),
        build_system_detail(
            base_time,
            11,
            "ws-003",
            "development",
            "10.42.3.13",
            "e8:2f:2a:44:11:03",
            "10.42.3.1",
            HealthStatus::Healthy,
            DeploymentStatus::NeverDeployed,
            Some(PipelineStage::ReadyForBuild),
            "24.05",
            "6.9.12",
            "Boot Only",
            "0.2.0",
            "1a82c0b1b6c0aaf4d3c3",
            "Intel Core i5-13600K 14-Core Processor",
            14,
            24.0,
            21_950,
            "WS-003-BRD",
            "1.2.8",
            false,
            false,
            false,
            None,
            CveSummary {
                critical: 0,
                high: 1,
                medium: 2,
                low: 3,
            },
            Some(flake_dev.clone()),
            10,
        ),
        build_system_detail(
            base_time,
            12,
            "ws-004",
            "development",
            "10.42.3.14",
            "e8:2f:2a:44:11:04",
            "10.42.3.1",
            HealthStatus::Healthy,
            DeploymentStatus::NeverDeployed,
            Some(PipelineStage::DryRun),
            "24.05",
            "6.9.12",
            "Boot Only",
            "0.2.0",
            "4a80ab7c9f40d2149a12",
            "AMD Ryzen 5 5600X 6-Core Processor",
            6,
            16.0,
            18_450,
            "WS-004-BRD",
            "1.1.4",
            false,
            false,
            false,
            None,
            CveSummary {
                critical: 0,
                high: 1,
                medium: 2,
                low: 3,
            },
            Some(flake_dev.clone()),
            14,
        ),
        build_system_detail(
            base_time,
            13,
            "ws-005",
            "development",
            "10.42.3.15",
            "e8:2f:2a:44:11:05",
            "10.42.3.1",
            HealthStatus::Healthy,
            DeploymentStatus::NeverDeployed,
            Some(PipelineStage::DryRun),
            "24.05",
            "6.9.10",
            "Boot Only",
            "0.2.0",
            "2cb1209f1d08cfed51a1",
            "Intel Core i5-12400 6-Core Processor",
            6,
            16.0,
            15_002,
            "WS-005-BRD",
            "1.1.3",
            false,
            false,
            false,
            None,
            CveSummary {
                critical: 0,
                high: 1,
                medium: 1,
                low: 2,
            },
            Some(flake_dev.clone()),
            20,
        ),
        build_system_detail(
            base_time,
            14,
            "ws-006",
            "development",
            "10.42.3.16",
            "e8:2f:2a:44:11:06",
            "10.42.3.1",
            HealthStatus::Healthy,
            DeploymentStatus::NeverDeployed,
            Some(PipelineStage::ReadyForBuild),
            "24.05",
            "6.9.10",
            "Boot Only",
            "0.2.0",
            "5c92110f09985e4c6bff",
            "Intel Core i3-12100 4-Core Processor",
            4,
            8.0,
            9_120,
            "WS-006-BRD",
            "1.0.9",
            false,
            false,
            false,
            None,
            CveSummary {
                critical: 0,
                high: 0,
                medium: 1,
                low: 2,
            },
            Some(flake_dev.clone()),
            28,
        ),
        build_system_detail(
            base_time,
            15,
            "ws-007",
            "development",
            "10.42.3.17",
            "e8:2f:2a:44:11:07",
            "10.42.3.1",
            HealthStatus::Healthy,
            DeploymentStatus::NeverDeployed,
            Some(PipelineStage::ReadyForBuild),
            "24.05",
            "6.9.10",
            "Boot Only",
            "0.2.0",
            "7f0110b5d7a7dc5e3d6d",
            "Intel Core i5-11600 6-Core Processor",
            6,
            16.0,
            8_540,
            "WS-007-BRD",
            "1.0.7",
            false,
            false,
            false,
            None,
            CveSummary {
                critical: 0,
                high: 0,
                medium: 1,
                low: 2,
            },
            Some(flake_dev.clone()),
            30,
        ),
        build_system_detail(
            base_time,
            16,
            "ws-008",
            "development",
            "10.42.3.18",
            "e8:2f:2a:44:11:08",
            "10.42.3.1",
            HealthStatus::Offline,
            DeploymentStatus::NeverDeployed,
            Some(PipelineStage::Unknown),
            "24.05",
            "6.9.8",
            "Boot Only",
            "0.1.9",
            "a20110ef11a5b0cc65f3",
            "Intel Core i5-10400 6-Core Processor",
            6,
            16.0,
            2_340,
            "WS-008-BRD",
            "0.9.1",
            false,
            false,
            false,
            None,
            CveSummary {
                critical: 0,
                high: 0,
                medium: 1,
                low: 1,
            },
            Some(flake_dev.clone()),
            240,
        ),
        build_system_detail(
            base_time,
            17,
            "edge-us-east",
            "production",
            "10.42.1.41",
            "d0:3e:7a:22:11:41",
            "10.42.1.1",
            HealthStatus::Healthy,
            DeploymentStatus::UpToDate,
            Some(PipelineStage::ReadyForDeploy),
            "24.11",
            "6.12.66",
            "Immediate",
            "0.2.1",
            "cc0ef72b3a2bd04f1e77",
            "Intel Xeon D-2146NT 8-Core Processor",
            8,
            32.0,
            61_220,
            "EDGE-USEAST",
            "1.6.0",
            true,
            false,
            false,
            Some("enforcing"),
            CveSummary {
                critical: 0,
                high: 1,
                medium: 3,
                low: 6,
            },
            Some(flake_core.clone()),
            4,
        ),
        build_system_detail(
            base_time,
            18,
            "edge-us-west",
            "production",
            "10.42.1.42",
            "d0:3e:7a:22:11:42",
            "10.42.1.1",
            HealthStatus::Warning,
            DeploymentStatus::NeverDeployed,
            Some(PipelineStage::ReadyForBuild),
            "24.11",
            "6.12.60",
            "Immediate",
            "0.2.0",
            "cb4f21c2e80d9c9a7a5a",
            "Intel Xeon D-2123IT 4-Core Processor",
            4,
            24.0,
            33_018,
            "EDGE-USWEST",
            "1.5.4",
            true,
            false,
            false,
            Some("enforcing"),
            CveSummary {
                critical: 1,
                high: 1,
                medium: 3,
                low: 5,
            },
            Some(flake_core.clone()),
            18,
        ),
        build_system_detail(
            base_time,
            19,
            "edge-eu-west",
            "production",
            "10.42.1.43",
            "d0:3e:7a:22:11:43",
            "10.42.1.1",
            HealthStatus::Healthy,
            DeploymentStatus::NeverDeployed,
            Some(PipelineStage::ReadyForBuild),
            "24.11",
            "6.12.60",
            "Immediate",
            "0.2.0",
            "a3bd1e33f2b44d8f7610",
            "Intel Xeon D-2145NT 8-Core Processor",
            8,
            32.0,
            27_880,
            "EDGE-EUWEST",
            "1.5.2",
            true,
            false,
            false,
            Some("enforcing"),
            CveSummary {
                critical: 0,
                high: 1,
                medium: 2,
                low: 4,
            },
            Some(flake_core.clone()),
            20,
        ),
        build_system_detail(
            base_time,
            20,
            "edge-eu-central",
            "production",
            "10.42.1.44",
            "d0:3e:7a:22:11:44",
            "10.42.1.1",
            HealthStatus::Healthy,
            DeploymentStatus::Unknown,
            Some(PipelineStage::Unknown),
            "24.11",
            "6.12.60",
            "Immediate",
            "0.2.0",
            "dde12cf299e0bf10a1d2",
            "Intel Xeon D-1718DML 8-Core Processor",
            8,
            16.0,
            25_120,
            "EDGE-EUCENTRAL",
            "1.4.8",
            false,
            false,
            false,
            Some("disabled"),
            CveSummary {
                critical: 0,
                high: 0,
                medium: 1,
                low: 2,
            },
            Some(flake_core.clone()),
            26,
        ),
        build_system_detail(
            base_time,
            21,
            "edge-ap-south",
            "production",
            "10.42.1.45",
            "d0:3e:7a:22:11:45",
            "10.42.1.1",
            HealthStatus::Offline,
            DeploymentStatus::Unknown,
            Some(PipelineStage::Unknown),
            "24.11",
            "6.12.58",
            "Immediate",
            "0.1.8",
            "ffe102c449b11c28c3cd",
            "Intel Atom C3758 8-Core Processor",
            8,
            16.0,
            4_350,
            "EDGE-APSOUTH",
            "1.4.2",
            false,
            false,
            false,
            Some("disabled"),
            CveSummary {
                critical: 0,
                high: 0,
                medium: 1,
                low: 2,
            },
            Some(flake_core.clone()),
            360,
        ),
    ]
}

fn build_system_detail(
    base_time: chrono::DateTime<Utc>,
    id: u128,
    hostname: &str,
    environment: &str,
    primary_ip: &str,
    primary_mac: &str,
    gateway_ip: &str,
    health_status: HealthStatus,
    deployment_status: DeploymentStatus,
    pipeline_stage: Option<PipelineStage>,
    nixos_version: &str,
    kernel: &str,
    deployment_policy: &str,
    agent_version: &str,
    store_hash: &str,
    cpu_brand: &str,
    cpu_cores: i32,
    memory_gb: f64,
    uptime_secs: i64,
    board_serial: &str,
    bios_version: &str,
    tpm_present: bool,
    secure_boot_enabled: bool,
    fips_mode: bool,
    selinux_status: Option<&str>,
    cve_counts: CveSummary,
    flake: Option<FlakeSummary>,
    last_seen_offset_hours: i64,
) -> SystemDetail {
    let last_seen = base_time - Duration::hours(last_seen_offset_hours);
    let is_active = !matches!(health_status, HealthStatus::Offline);
    let store_path = if matches!(deployment_status, DeploymentStatus::Unknown) {
        None
    } else {
        Some(format!(
            "/nix/store/{store_hash}-nixos-system-{hostname}-{nixos_version}"
        ))
    };

    SystemDetail {
        id: Uuid::from_u128(id),
        hostname: hostname.to_string(),
        environment: Some(environment.to_string()),
        is_active,
        deployment_policy: deployment_policy.to_string(),
        health_status,
        deployment_status,
        pipeline_stage,
        nixos_version: Some(nixos_version.to_string()),
        kernel: Some(kernel.to_string()),
        agent_version: Some(agent_version.to_string()),
        current_store_path: store_path,
        hardware: SystemHardwareInfo {
            cpu_brand: Some(cpu_brand.to_string()),
            cpu_cores: Some(cpu_cores),
            memory_gb: Some(memory_gb),
            uptime_secs: Some(uptime_secs),
            board_serial: Some(board_serial.to_string()),
            bios_version: Some(bios_version.to_string()),
        },
        network: SystemNetworkInfo {
            primary_ip: Some(primary_ip.to_string()),
            primary_mac: Some(primary_mac.to_string()),
            gateway_ip: Some(gateway_ip.to_string()),
        },
        security: SystemSecurityInfo {
            tpm_present: Some(tpm_present),
            secure_boot_enabled: Some(secure_boot_enabled),
            fips_mode: Some(fips_mode),
            selinux_status: selinux_status.map(|value| value.to_string()),
        },
        cve_counts,
        flake,
        last_seen: Some(last_seen),
        created_at: base_time - Duration::days(420),
        updated_at: base_time - Duration::hours(1),
    }
}

