use chrono::{DateTime, Utc};

use crate::api::models::{
    CveSummary, DeploymentStatus, FlakeSummary, HealthStatus, PipelineStage, SystemDetail,
};

pub(super) fn additional_systems(
    base_time: DateTime<Utc>,
    flake_core: &FlakeSummary,
    flake_staging: &FlakeSummary,
    flake_dev: &FlakeSummary,
) -> Vec<SystemDetail> {
    vec![
        super::build_system_detail(
            base_time,
            9,
            "ws-001",
            "development",
            "10.42.3.11",
            "e8:2f:2a:44:11:01",
            "10.42.3.1",
            HealthStatus::Healthy,
            DeploymentStatus::Behind,
            Some(PipelineStage::BuildComplete),
            "24.05",
            "6.9.12",
            "Manual",
            "0.2.1",
            "d10c01f3fda6b36b845e",
            "AMD Ryzen 7 5800X 8-Core Processor",
            8,
            32.0,
            54_210,
            "WS-001-BRD",
            "1.3.1",
            false,
            false,
            false,
            Some("disabled"),
            CveSummary {
                critical: 0,
                high: 1,
                medium: 2,
                low: 4,
            },
            Some(flake_dev.clone()),
            2,
        ),
        super::build_system_detail(
            base_time,
            10,
            "ws-002",
            "development",
            "10.42.3.12",
            "e8:2f:2a:44:11:02",
            "10.42.3.1",
            HealthStatus::Healthy,
            DeploymentStatus::NeverDeployed,
            Some(PipelineStage::ReadyForBuild),
            "24.05",
            "6.9.12",
            "Boot Only",
            "0.2.0",
            "f21b209f2a44d19abce9",
            "Intel Core i7-12700 12-Core Processor",
            12,
            32.0,
            29_300,
            "WS-002-BRD",
            "1.2.8",
            false,
            false,
            false,
            None,
            CveSummary {
                critical: 0,
                high: 0,
                medium: 2,
                low: 3,
            },
            Some(flake_dev.clone()),
            5,
        ),
        super::build_system_detail(
            base_time,
            11,
            "ws-003",
            "development",
            "10.42.3.13",
            "e8:2f:2a:44:11:03",
            "10.42.3.1",
            HealthStatus::Healthy,
            DeploymentStatus::NeverDeployed,
            Some(PipelineStage::ReadyForBuild),
            "24.05",
            "6.9.12",
            "Boot Only",
            "0.2.0",
            "1a82c0b1b6c0aaf4d3c3",
            "Intel Core i5-13600K 14-Core Processor",
            14,
            24.0,
            21_950,
            "WS-003-BRD",
            "1.2.8",
            false,
            false,
            false,
            None,
            CveSummary {
                critical: 0,
                high: 1,
                medium: 2,
                low: 3,
            },
            Some(flake_dev.clone()),
            10,
        ),
        super::build_system_detail(
            base_time,
            12,
            "ws-004",
            "development",
            "10.42.3.14",
            "e8:2f:2a:44:11:04",
            "10.42.3.1",
            HealthStatus::Healthy,
            DeploymentStatus::NeverDeployed,
            Some(PipelineStage::DryRun),
            "24.05",
            "6.9.12",
            "Boot Only",
            "0.2.0",
            "4a80ab7c9f40d2149a12",
            "AMD Ryzen 5 5600X 6-Core Processor",
            6,
            16.0,
            18_450,
            "WS-004-BRD",
            "1.1.4",
            false,
            false,
            false,
            None,
            CveSummary {
                critical: 0,
                high: 1,
                medium: 2,
                low: 3,
            },
            Some(flake_dev.clone()),
            14,
        ),
        super::build_system_detail(
            base_time,
            13,
            "ws-005",
            "development",
            "10.42.3.15",
            "e8:2f:2a:44:11:05",
            "10.42.3.1",
            HealthStatus::Healthy,
            DeploymentStatus::NeverDeployed,
            Some(PipelineStage::DryRun),
            "24.05",
            "6.9.10",
            "Boot Only",
            "0.2.0",
            "2cb1209f1d08cfed51a1",
            "Intel Core i5-12400 6-Core Processor",
            6,
            16.0,
            15_002,
            "WS-005-BRD",
            "1.1.3",
            false,
            false,
            false,
            None,
            CveSummary {
                critical: 0,
                high: 1,
                medium: 1,
                low: 2,
            },
            Some(flake_dev.clone()),
            20,
        ),
        super::build_system_detail(
            base_time,
            14,
            "ws-006",
            "development",
            "10.42.3.16",
            "e8:2f:2a:44:11:06",
            "10.42.3.1",
            HealthStatus::Healthy,
            DeploymentStatus::NeverDeployed,
            Some(PipelineStage::ReadyForBuild),
            "24.05",
            "6.9.10",
            "Boot Only",
            "0.2.0",
            "5c92110f09985e4c6bff",
            "Intel Core i3-12100 4-Core Processor",
            4,
            8.0,
            9_120,
            "WS-006-BRD",
            "1.0.9",
            false,
            false,
            false,
            None,
            CveSummary {
                critical: 0,
                high: 0,
                medium: 1,
                low: 2,
            },
            Some(flake_dev.clone()),
            28,
        ),
        super::build_system_detail(
            base_time,
            15,
            "ws-007",
            "development",
            "10.42.3.17",
            "e8:2f:2a:44:11:07",
            "10.42.3.1",
            HealthStatus::Healthy,
            DeploymentStatus::NeverDeployed,
            Some(PipelineStage::ReadyForBuild),
            "24.05",
            "6.9.10",
            "Boot Only",
            "0.2.0",
            "7f0110b5d7a7dc5e3d6d",
            "Intel Core i5-11600 6-Core Processor",
            6,
            16.0,
            8_540,
            "WS-007-BRD",
            "1.0.7",
            false,
            false,
            false,
            None,
            CveSummary {
                critical: 0,
                high: 0,
                medium: 1,
                low: 2,
            },
            Some(flake_dev.clone()),
            30,
        ),
        super::build_system_detail(
            base_time,
            16,
            "ws-008",
            "development",
            "10.42.3.18",
            "e8:2f:2a:44:11:08",
            "10.42.3.1",
            HealthStatus::Offline,
            DeploymentStatus::NeverDeployed,
            Some(PipelineStage::Unknown),
            "24.05",
            "6.9.8",
            "Boot Only",
            "0.1.9",
            "a20110ef11a5b0cc65f3",
            "Intel Core i5-10400 6-Core Processor",
            6,
            16.0,
            2_340,
            "WS-008-BRD",
            "0.9.1",
            false,
            false,
            false,
            None,
            CveSummary {
                critical: 0,
                high: 0,
                medium: 1,
                low: 1,
            },
            Some(flake_dev.clone()),
            240,
        ),
        super::build_system_detail(
            base_time,
            17,
            "edge-us-east",
            "production",
            "10.42.1.41",
            "d0:3e:7a:22:11:41",
            "10.42.1.1",
            HealthStatus::Healthy,
            DeploymentStatus::UpToDate,
            Some(PipelineStage::ReadyForDeploy),
            "24.11",
            "6.12.66",
            "Immediate",
            "0.2.1",
            "cc0ef72b3a2bd04f1e77",
            "Intel Xeon D-2146NT 8-Core Processor",
            8,
            32.0,
            61_220,
            "EDGE-USEAST",
            "1.6.0",
            true,
            false,
            false,
            Some("enforcing"),
            CveSummary {
                critical: 0,
                high: 1,
                medium: 3,
                low: 6,
            },
            Some(flake_core.clone()),
            4,
        ),
        super::build_system_detail(
            base_time,
            18,
            "edge-us-west",
            "production",
            "10.42.1.42",
            "d0:3e:7a:22:11:42",
            "10.42.1.1",
            HealthStatus::Warning,
            DeploymentStatus::NeverDeployed,
            Some(PipelineStage::ReadyForBuild),
            "24.11",
            "6.12.60",
            "Immediate",
            "0.2.0",
            "cb4f21c2e80d9c9a7a5a",
            "Intel Xeon D-2123IT 4-Core Processor",
            4,
            24.0,
            33_018,
            "EDGE-USWEST",
            "1.5.4",
            true,
            false,
            false,
            Some("enforcing"),
            CveSummary {
                critical: 1,
                high: 1,
                medium: 3,
                low: 5,
            },
            Some(flake_core.clone()),
            18,
        ),
        super::build_system_detail(
            base_time,
            19,
            "edge-eu-west",
            "production",
            "10.42.1.43",
            "d0:3e:7a:22:11:43",
            "10.42.1.1",
            HealthStatus::Healthy,
            DeploymentStatus::NeverDeployed,
            Some(PipelineStage::ReadyForBuild),
            "24.11",
            "6.12.60",
            "Immediate",
            "0.2.0",
            "a3bd1e33f2b44d8f7610",
            "Intel Xeon D-2145NT 8-Core Processor",
            8,
            32.0,
            27_880,
            "EDGE-EUWEST",
            "1.5.2",
            true,
            false,
            false,
            Some("enforcing"),
            CveSummary {
                critical: 0,
                high: 1,
                medium: 2,
                low: 4,
            },
            Some(flake_core.clone()),
            20,
        ),
        super::build_system_detail(
            base_time,
            20,
            "edge-eu-central",
            "production",
            "10.42.1.44",
            "d0:3e:7a:22:11:44",
            "10.42.1.1",
            HealthStatus::Healthy,
            DeploymentStatus::Unknown,
            Some(PipelineStage::Unknown),
            "24.11",
            "6.12.60",
            "Immediate",
            "0.2.0",
            "dde12cf299e0bf10a1d2",
            "Intel Xeon D-1718DML 8-Core Processor",
            8,
            16.0,
            25_120,
            "EDGE-EUCENTRAL",
            "1.4.8",
            false,
            false,
            false,
            Some("disabled"),
            CveSummary {
                critical: 0,
                high: 0,
                medium: 1,
                low: 2,
            },
            Some(flake_core.clone()),
            26,
        ),
        super::build_system_detail(
            base_time,
            21,
            "edge-ap-south",
            "production",
            "10.42.1.45",
            "d0:3e:7a:22:11:45",
            "10.42.1.1",
            HealthStatus::Offline,
            DeploymentStatus::Unknown,
            Some(PipelineStage::Unknown),
            "24.11",
            "6.12.58",
            "Immediate",
            "0.1.8",
            "ffe102c449b11c28c3cd",
            "Intel Atom C3758 8-Core Processor",
            8,
            16.0,
            4_350,
            "EDGE-APSOUTH",
            "1.4.2",
            false,
            false,
            false,
            Some("disabled"),
            CveSummary {
                critical: 0,
                high: 0,
                medium: 1,
                low: 2,
            },
            Some(flake_core.clone()),
            360,
        ),
    ]
}
